"""Initial country migration

Revision ID: d041a3a1db1f
Revises: 13346826bc9f
Create Date: 2024-10-30 09:15:47.127359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd041a3a1db1f'
down_revision: Union[str, None] = '13346826bc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1=Active,0=Inactive'),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='countries_pkey'),
    schema='hr'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries', schema='hr')
    # ### end Alembic commands ###
